/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as CompletarPerfilRouteImport } from './routes/completar-perfil'
import { Route as HidratacaoRouteImport } from './routes/hidratacao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModulosRouteImport } from './routes/modulos'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as CheckInHistoricoRouteImport } from './routes/check-in_.historico'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarPerfilRoute = CompletarPerfilRouteImport.update({
  id: '/completar-perfil',
  path: '/completar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const HidratacaoRoute = HidratacaoRouteImport.update({
  id: '/hidratacao',
  path: '/hidratacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosRoute = ModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInHistoricoRoute = CheckInHistoricoRouteImport.update({
  id: '/check-in_/historico',
  path: '/check-in/historico',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/check-in': typeof CheckInRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/hidratacao': typeof HidratacaoRoute
  '/login': typeof LoginRoute
  '/modulos': typeof ModulosRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/registro': typeof RegistroRoute
  '/tarefas': typeof TarefasRoute
  '/check-in/historico': typeof CheckInHistoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/check-in': typeof CheckInRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/hidratacao': typeof HidratacaoRoute
  '/login': typeof LoginRoute
  '/modulos': typeof ModulosRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/registro': typeof RegistroRoute
  '/tarefas': typeof TarefasRoute
  '/check-in/historico': typeof CheckInHistoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/check-in': typeof CheckInRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/hidratacao': typeof HidratacaoRoute
  '/login': typeof LoginRoute
  '/modulos': typeof ModulosRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/registro': typeof RegistroRoute
  '/tarefas': typeof TarefasRoute
  '/check-in_/historico': typeof CheckInHistoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/check-in'
    | '/completar-perfil'
    | '/hidratacao'
    | '/login'
    | '/modulos'
    | '/nova-senha'
    | '/registro'
    | '/tarefas'
    | '/check-in/historico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/check-in'
    | '/completar-perfil'
    | '/hidratacao'
    | '/login'
    | '/modulos'
    | '/nova-senha'
    | '/registro'
    | '/tarefas'
    | '/check-in/historico'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/check-in'
    | '/completar-perfil'
    | '/hidratacao'
    | '/login'
    | '/modulos'
    | '/nova-senha'
    | '/registro'
    | '/tarefas'
    | '/check-in_/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  CheckInRoute: typeof CheckInRoute
  CompletarPerfilRoute: typeof CompletarPerfilRoute
  HidratacaoRoute: typeof HidratacaoRoute
  LoginRoute: typeof LoginRoute
  ModulosRoute: typeof ModulosRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  RegistroRoute: typeof RegistroRoute
  TarefasRoute: typeof TarefasRoute
  CheckInHistoricoRoute: typeof CheckInHistoricoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-perfil': {
      id: '/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof CompletarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidratacao': {
      id: '/hidratacao'
      path: '/hidratacao'
      fullPath: '/hidratacao'
      preLoaderRoute: typeof HidratacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos': {
      id: '/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof ModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in_/historico': {
      id: '/check-in_/historico'
      path: '/check-in/historico'
      fullPath: '/check-in/historico'
      preLoaderRoute: typeof CheckInHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  CheckInRoute: CheckInRoute,
  CompletarPerfilRoute: CompletarPerfilRoute,
  HidratacaoRoute: HidratacaoRoute,
  LoginRoute: LoginRoute,
  ModulosRoute: ModulosRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  RegistroRoute: RegistroRoute,
  TarefasRoute: TarefasRoute,
  CheckInHistoricoRoute: CheckInHistoricoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
